/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.ArrayList;
import java.util.logging.Level;
 import java.util.logging.Logger;
import javax.swing.JButton;
/**
 *
 * @author nicni
 */
public class PopUp extends javax.swing.JFrame {
String cardImage ="";
Game game;
ArrayList<UnoCard>playerHand;
int choice;
ArrayList<JButton>cardButtons;
GameStage gamestage;
JButton topCardButton;
UnoCard.Color declaredColor;
    
Public PopUp(){
    
    public PopUp(String cardName, Game game, int index,ArrayList<JButton> cardButtons, GameStage gamestage, JButton topCardButton) 
        {
            initComponents();
            cardImage=cardName;
            this.game=game;
            playerHand= game.getPlayerHand(game.getCurrentPlayer());
            choice =index;
            this.cardButtons=cardButtons;
            cardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGs/large" +cardImage +".png")));
            this.gamestage=gamestage;
            this.topCardButton = topCardButton;
        
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void useCardButtonActionPerformed(java.awt.event.ActionEvent evt)
        {
        PickColorFrame pickColor= new PickColorFrame(this);
        declaredColor = pickColor.choseColor(playerHand.get(choice));
        
        if(declaredColor!=null){
        try{
            game.submitPlayerCard(game.getCurrentPlayer(),playerHand.get(choice),declaredColor);
        }
        catch(InvalidColorSubmissionException ex){
        Logger.getLogger(PopUp.class .getName()).log(Level.SEVERE,null,ex);
        }
        catch(InvalidValueSubmissionException ex){
        Logger.getLogger(PopUp.class .getName()).log(Level.SEVERE,null,ex);
        }
        catch (InvalidPlayerTurnException ex){
        Logger.getLogger(PopUp.class .getName()).log(Level.SEVERE,null,ex);
        }
        
        this.revalidate();
        if(declaredColor!=UnoCard.Color.Wild){
        gameStage.setPidName(game.getCurrentPlayer());
        gameStage.setButtonIcons();
        topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PNGs/small" +game.getTopCardImage())));
       this.dispose();
        }
        }
        
        
        }
        private void canvelButtonActionPerformed(java.awt.event.ActionEvent evt)
        {
        this.dispose();
        }
        
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp().setVisible(true);
            }
        })
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
